rootProject.name = "order-managment-system"
include("actuator")
include("delivery")
include("discovery")
include("gateway")
include("inventory")
include("order")
include("payment")
include("general")
include("starter-utils")
