apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-deployment
  namespace: oms
spec:
  serviceName: kafka
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: configs
