apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db-deployment
  namespace: oms
spec:
  serviceName: payment-db
  replicas: 1
  selector:
    matchLabels:
      component: payment-db
  template:
    metadata:
      labels:
        component: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: payment
          envFrom:
            - configMapRef:
                name: configs
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: payment-db-storage
      volumes:
        - name: payment-db-storage
          persistentVolumeClaim:
            claimName: payment-db-pvc
