apiVersion: v1
kind: Pod
metadata:
  name: discovery-service
  labels:
    component: discovery
spec:
  containers:
    - name: discovery
      image: fenrisv/discovery:0.0.1
      ports:
        - containerPort: 8000
      env:
        - name: ZIPKIN_DOMAIN
          value: zipkin-service
        - name: OMS_DISCOVERY_DOMAIN
          value: discovery-service
