apiVersion: v1
kind: Pod
metadata:
  name: order-app
  labels:
    component: order
spec:
  containers:
    - name: order
      image: fenrisv/order:0.0.1
      ports:
        - containerPort: 8004
      env:
        - name: ORDER_DOMAIN
          value: order-service
        - name: DISCOVERY_DOMAIN
          value: discovery-service
        - name: ZIPKIN_DOMAIN
          value: zipkin-service
        - name: ADMIN_DOMAIN
          value: actuator-service
        - name: KAFKA_HOST
          value: kafka-service
        - name: MONGO_ORDER_HOST
          value: order-mongo-service
        - name: MONGO_ORDER_PORT
          value: "27017"
