apiVersion: v1
kind: Pod
metadata:
  name: payment-db
  labels:
    component: payment-db
spec:
  containers:
    - name: payment-db
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_DB
          value: payment
