apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-app
  labels:
    component: zookeeper
spec:
  containers:
    - name: zookeeper
      image: bitnami/zookeeper:latest
      ports:
        - containerPort: 2181
      env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
