spring:
  cloud:
    gateway:
      routes:
        - id: order_swagger
          uri: lb://${ORDER_DOMAIN:order}
          predicates:
            - Path=/api/v1/order/v3/**

        - id: order
          uri: lb://${ORDER_DOMAIN:order}
          predicates:
            - Path=/api/v1/order/**
          filters:
            - StripPrefix=3

security:
  excluded:
    get: >
      /api/v1/user/password,
      /api/v1/user/verify,

      /webjars/**,
      /swagger,
      /v3/**

    post: >
      /api/v1/user/password/reset,
      /api/v1/user/register,
      /api/v1/user/refresh,
