grpc:
  server:
    port: ${SECURITY_GRPC_PORT:9001}
    reflectionServiceEnabled: false

spring:
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    name: ${SMTP_USERNAME:OMS}
    email: ${SMTP_EMAIL:example@gmail.com}
    password: ${SMTP_PASSWORD:secret}

  cache:
    type: caffeine

  boot:
    admin:
      client:
        url: ${DP_SERVICE_PROTOCOL:http://}${ADMIN_DOMAIN:localhost}:${DP_ADMIN_PORT:8999}
        instance:
          service-url: ${DP_SERVICE_PROTOCOL:http://}${GATEWAY_DOMAIN:localhost}:${GATEWAY_PORT:8080}
          health-url: ${DP_SERVICE_PROTOCOL:http://}${GATEWAY_DOMAIN:localhost}:${GATEWAY_PORT:8080}/actuator/health
          management-url: ${DP_SERVICE_PROTOCOL:http://}${GATEWAY_DOMAIN:localhost}:${GATEWAY_PORT:8080}/actuator

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
    url: jdbc:postgresql://${GATEWAY_DB_HOST:localhost}:${GATEWAY_DB_PORT:6430}/${GATEWAY_DB_NAME:auth}?stringtype=unspecified
    user: ${GATEWAY_DB_USER:user}
    password: ${GATEWAY_DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  r2dbc:
    url: r2dbc:postgresql://${GATEWAY_DB_HOST:localhost}:${GATEWAY_DB_PORT:6430}/${GATEWAY_DB_NAME:auth}?stringtype=unspecified
    username: ${GATEWAY_DB_USER:user}
    password: ${GATEWAY_DB_PASSWORD:secret}

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_PROTOCOL:http://}${DISCOVERY_DOMAIN:localhost}:${OMS_DISCOVERY_PORT:8000}/eureka

app:
  domain: ${APP_DOMAIN:http://localhost:8080}
  auth:
    jwt:
      secret: ${JWT_SECRET:/ukozASJfFYdplkdQp8sP+Di/7tk00TTIe+SDX3+LP3te7VU3fFcI7Ykgm7AqOF1TVXApKBOchQ212w4Qxuzzg==}
      expiration: 1d
    refresh:
      secret: ${REFRESH_SECRET:/ukozASJfFYdplkdQp8sP+Di/7tk00TTIe+SDX3+LP3te7VU3fFcI7Ykgm7AqOF1TVXApKBOchQ212w4Qxuzzg==}
      expiration: 30d

  ninjas:
    base-url: https://api.api-ninjas.com/v1/
    api-key: ${NINJAS_API_KEY:3HPpw8Okft+27wVO4pDuow==h4XmOUNKkShZU3if}

springdoc:
  domain: ${APP_DOMAIN:http://localhost:8080}
  prefix: /api/v1
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs
    enabled: true

starter:
  utils:
    web-client: true
    jwt: true
