spring:
  application:
    name: order

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_PROTOCOL:http://}${DISCOVERY_DOMAIN:localhost}:${OMS_DISCOVERY_PORT:8000}/eureka

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: 'health,prometheus'

  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
