management:
  endpoints:
    web:
      exposure:
        include: '*'
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      jvm: true

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_DOMAIN:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
