apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: delivery
  template:
    metadata:
      labels:
        component: delivery
    spec:
      containers:
        - name: delivery
          image: fenrisv/delivery:0.0.1
          ports:
            - containerPort: 8002
          env:
            - name: DELIVERY_DOMAIN
              value: delivery-service
            - name: DISCOVERY_DOMAIN
              value: discovery-service
            - name: ZIPKIN_DOMAIN
              value: zipkin-service
            - name: ADMIN_DOMAIN
              value: actuator-service
            - name: KAFKA_HOST
              value: kafka-service
