apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: gateway
  template:
    metadata:
      labels:
        component: gateway
    spec:
      containers:
        - name: gateway
          image: fenrisv/gateway:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: GATEWAY_DOMAIN
              value: gateway-service
            - name: GATEWAY_DB_HOST
              value: security-db-service
            - name: GATEWAY_DB_PORT
              value: "5432"
            - name: GATEWAY_DB_USER
              value: user
            - name: GATEWAY_DB_PASSWORD
              value: secret
            - name: GATEWAY_DB_NAME
              value: auth
            - name: DISCOVERY_DOMAIN
              value: discovery-service
            - name: ZIPKIN_DOMAIN
              value: zipkin-service
            - name: ADMIN_DOMAIN
              value: actuator-service
