apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: oms
spec:
  replicas: 4
  selector:
    matchLabels:
      component: gateway
  template:
    metadata:
      labels:
        component: gateway
    spec:
      containers:
        - name: gateway
          image: fenrisv/gateway:0.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configs
