apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  namespace: oms
spec:
  replicas: 2
  selector:
    matchLabels:
      component: inventory
  template:
    metadata:
      labels:
        component: inventory
    spec:
      containers:
        - name: inventory
          image: fenrisv/inventory:0.0.1
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: configs
