apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: oms
spec:
  replicas: 2
  selector:
    matchLabels:
      component: order
  template:
    metadata:
      labels:
        component: order
    spec:
      containers:
        - name: order
          image: fenrisv/order:0.0.1
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: configs
