apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: oms
spec:
  replicas: 2
  selector:
    matchLabels:
      component: payment
  template:
    metadata:
      labels:
        component: payment
    spec:
      containers:
        - name: payment
          image: fenrisv/payment:0.0.1
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: configs
