apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: actuator-deployment
  namespace: oms
spec:
  selector:
    matchLabels:
      component: actuator
  template:
    metadata:
      labels:
        component: actuator
    spec:
      containers:
        - name: actuator
          image: fenrisv/actuator:0.0.1
          ports:
            - containerPort: 8999
