apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-deployment
  namespace: monitoring
spec:
  selector:
    matchLabels:
      component: grafana
  template:
    metadata:
      labels:
        component: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: /etc/grafana/provisioning
              name: grafana-storage
      volumes:
        - name: grafana-storage
          hostPath:
            path: /run/desktop/mnt/host/c/www/order-managment-system/grafana/provisioning
