apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zipkin-deployment
  namespace: oms
spec:
  selector:
    matchLabels:
      component: zipkin
  template:
    metadata:
      labels:
        component: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
