apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-auth-role
  namespace: oms
rules:
  - verbs:
      - get
      - list
    resources:
      - secrets
    apiGroups:
      - ""
