apiVersion: v1
kind: Service
metadata:
  name: actuator-service
spec:
  type: ClusterIP
  ports:
    - name: actuator
      protocol: TCP
      port: 8999
      targetPort: 8999
  selector:
    component: actuator
