apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: oms
spec:
  type: ClusterIP
  ports:
    - name: discovery
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    component: discovery
