apiVersion: v1
kind: Service
metadata:
  name: order-mongo-service
  namespace: oms
spec:
  type: ClusterIP
  ports:
    - name: order-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    component: order-mongo
