apiVersion: v1
kind: Service
metadata:
  name: payment-db-service
  namespace: oms
spec:
  type: ClusterIP
  ports:
    - name: payment-db
      protocol: TCP
      port: 5433
      targetPort: 5432
  selector:
    component: payment-db
