apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: oms
spec:
  type: NodePort
  ports:
    - name: vault
      protocol: TCP
      port: 8200
      targetPort: 8200
      nodePort: 31000
  selector:
    component: vault
