apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  type: ClusterIP
  ports:
    - name: zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
  selector:
    component: zipkin
