apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  ports:
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181
  selector:
    component: zookeeper
