server:
  port: ${OMS_DISCOVERY_PORT:8000}

spring:
  application:
    name: discovery

  profiles:
    active: native

  cloud:
    config:
      server:
        prefix: /config
        native:
          search-locations: file:${OMS_CONFIG_PATH:./config/}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

  dashboard:
    path: /admin/dashboard
    enabled: true

  client:
    fetch-registry: false
    enabled: true
    service-url:
      defaultZone: ${OMS_SERVICE_PROTOCOL:http://}${OMS_DISCOVERY_DOMAIN:localhost}:${OMS_DISCOVERY_PORT:8000}/eureka

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_DOMAIN:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
