server:
  port: ${OMS_DISCOVERY_PORT:8000}

spring:
  application:
    name: discovery

  profiles:
    active: native

  cloud:
    config:
      server:
        prefix: /config
        native:
          search-locations: file:${OMS_CONFIG_PATH:./config/}

eureka:
  dashboard:
    path: /admin/dashboard
    enabled: true

  client:
    fetch-registry: false
    enabled: true
    service-url:
      defaultZone: ${OMS_SERVICE_PROTOCOL:http://}${OMS_DISCOVERY_DOMAIN:localhost}:${OMS_DISCOVERY_PORT:8080}/eureka

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

  prometheus:
    metrics:
      export:
        enabled: true
